main:
  config:
    kafka:
      topic: anomalies
      offsets: earliest
      consumerGroupId: consumer-mongo-1
      bootstrapAddress: 172.18.0.1:32772
spring:
  data:
    mongodb:
      host: 172.19.0.2
      port: 27023
      database: db

